---
# GitLab CI for FranklinWH Battery Scheduler
# PGE Time-of-Use pricing optimization
# Off-peak 9PM-7AM (all day weekends) 9.08 cents/kWh
# Mid-Peak 7AM-5PM (weekdays only) 16.99 cents/kWh
# Peak 5PM-9PM (weekdays only) 43.89 cents/kWh

stages:
  - battery-control

variables:
  # These should be set as CI/CD variables in GitLab project settings
  # FRANKLIN_EMAIL
  # FRANKLIN_PASSWORD
  # FRANKLIN_GATEWAY_ID
  # ENABLE_GITLAB_CI
  # gitlab recommends inputs instead of variables
  # but their glab schedule tools doesn't seem to support using inputs
  SOC_TARGET: "65"

set_battery_soc:
  stage: battery-control
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y curl openssl
    - chmod +x set_soc.sh
  script:
    - ./set_soc.sh $SOC_TARGET
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $ENABLE_GITLAB_CI == "true"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  tags:
