name: FranklinWH Battery Scheduler
on:
  schedule:
    - cron: '50 12 * * *'  # 6:50 AM PDT (UTC-7)
    - cron: '55 23 * * *'  # 4:55 PM PDT (UTC-7)
    - cron: '34 2 * * *'   # 7:25 PM PDT (UTC-7)
    - cron: '5 4 * * *'    # 9:05 PM PDT (UTC-7)

  workflow_dispatch:
    inputs:
      soc:
        description: 'SOC percentage (0-100)'
        required: true
        default: '65'

jobs:
  set-battery-soc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug schedule info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Schedule: ${{ github.event.schedule }}"
          echo "Full event context:"
          echo '${{ toJson(github.event) }}'

      - name: Set morning SOC (65%)
        if: github.event.schedule == '50 12 * * *'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./set_soc.sh 65

      - name: Set afternoon SOC (35%)
        if: github.event.schedule == '55 23 * * *'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./set_soc.sh 35

      - name: Set 7:23PM SOC (22%)
        if: github.event.schedule == '34 2 * * *'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./set_soc.sh 22

      - name: Set evening SOC (95%)
        if: github.event.schedule == '5 4 * * *'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./set_soc.sh 95

      - name: Set manual SOC
        if: github.event_name == 'workflow_dispatch'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./set_soc.sh ${{ github.event.inputs.soc }}
