name: FranklinWH Battery Scheduler
on:
  # PGE https://portlandgeneral.com/about/info/pricing-plans/time-of-day
  # Off-peak 9PM-7AM (all day weekends) 9.08 cents/kWh
  # Mid-Peak 7AM-5PM (weekdays only) 16.99 cents/kWh
  # Peak 7AM-5PM (weekdays only) 43.89 cents/kWh
  schedule:
    - cron: '50 12 * * 1-5'  # 6:50 AM PDT (UTC-7) 65% Mid-Peak allow some battery drain, solar will often cover
    - cron: '00 23 * * 1-5'  # 4:00 PM PDT (UTC-7) 95% Peak prep charge to avoid peak grid usage.  Usually already here from solar except on cloudy days
    - cron: '55 23 * * 1-5'  # 4:55 PM PDT (UTC-7) 35% Peak let battery drain during peak to avoid grid use
    - cron: '10 4 * * 1-5'   # 9:10 PM PDT (UTC-7) 95% Off-peak recharge battery

  workflow_dispatch:
    inputs:
      soc:
        description: 'SOC percentage (0-100)'
        required: true
        default: '65'

jobs:
  set-battery-soc:
    runs-on: ubuntu-latest
    if: vars.ENABLE_GITHUB_ACTIONS == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug schedule info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Schedule: ${{ github.event.schedule }}"
          echo "Full event context:"
          echo '${{ toJson(github.event) }}'

      - name: mid-peak 65% 6:50 AM
        if: github.event.schedule == '50 12 * * 1-5'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./franklin set-soc 65

      - name: peak prep 95% 4:00 PM
        if: github.event.schedule == '00 23 * * 1-5'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./franklin set-soc 95

      - name: peak drain 35% 4:55 PM
        if: github.event.schedule == '55 23 * * 1-5'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./franklin set-soc 35

      - name: off-peak recharge 95% 9:10 PM
        if: github.event.schedule == '10 4 * * 1-5'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./franklin set-soc 95

      - name: Set manual SOC
        if: github.event_name == 'workflow_dispatch'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./franklin set-soc ${{ github.event.inputs.soc }}
