name: FranklinWH Battery Scheduler

on:
  schedule:
    # 6:50 AM UTC (adjust for your timezone)
    - cron: '50 13 * * *'  # 6:50 AM PST (UTC-8)
    # 4:55 PM UTC (adjust for your timezone)
    - cron: '55 0 * * *'   # 4:55 PM PST (UTC-8)
    # 7:07 PM PDT (adjust for your timezone)
    - cron: '7 2 * * *'   # 7:07 PM PDT (UTC-7)
    # 10:00 PM UTC (adjust for your timezone)
    - cron: '0 6 * * *'    # 10:00 PM PST (UTC-8)

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      soc:
        description: 'SOC percentage (0-100)'
        required: true
        default: '65'

jobs:
  set-battery-soc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set morning SOC (65%)
        if: github.event.schedule == '50 13 * * *'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./set_soc.sh 65

      - name: Set afternoon SOC (35%)
        if: github.event.schedule == '55 0 * * *'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./set_soc.sh 35

      - name: Set 7:07PM SOC (22%)
        if: github.event.schedule == '7 2 * * *'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./set_soc.sh 22

      - name: Set evening SOC (95%)
        if: github.event.schedule == '0 6 * * *'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./set_soc.sh 95

      - name: Set manual SOC
        if: github.event_name == 'workflow_dispatch'
        env:
          FRANKLIN_EMAIL: ${{ secrets.FRANKLIN_EMAIL }}
          FRANKLIN_PASSWORD: ${{ secrets.FRANKLIN_PASSWORD }}
          FRANKLIN_GATEWAY_ID: ${{ secrets.FRANKLIN_GATEWAY_ID }}
        run: ./set_soc.sh ${{ github.event.inputs.soc }}
